### ISSUE TITLE
Fix floating footer

### ISSUE THREAD

**Issue by JulianSteinmann** [greenferries/greenferries#14]
![image](https://user-images.githubusercontent.com/35849163/74677335-e917d000-51af-11ea-8029-1f16b58f4438.png)

Can be fixed with this on the div with class 'css-1q2uwxt'
` height: 100vh; display: flex;`

Or if you want to still see the footer you could use a fixed height for the footer and use something like this:
` height: calc(100vh - 300px); display: flex;`

**Comment by adipasquale** [comment]
thanks for opening the issue and the solution @JulianSteinmann it should be fixed in the next release 👍
