### ISSUE TITLE
Changer le lien du compte github

### ISSUE THREAD

**Issue by laem** [greenferries/greenferries#72]
![image](https://github.com/greenferries/greenferries/assets/1177762/d81d2751-425c-480f-9813-fc2209e2e981)

Car actuellement, le squateur de domaine a redirigé le lien vers ça 
![image](https://github.com/greenferries/greenferries/assets/1177762/36afd1cc-8c62-4818-9218-7fa6b90d3397)

:sweat_smile:

**Comment by laem** [comment]
@adipasquale

**Comment by adipasquale** [comment]
merci ! c’est fait

**Comment by laem** [comment]
J'ai mis à jour les références vers netlify sur https://hackmd.io/@laem/empreinte-ferry
